<?
    require( $_SERVER[ "DOCUMENT_ROOT" ] . "/bitrix/header.php" );
    $APPLICATION->SetTitle("Диагноз детально");
?><? $APPLICATION->IncludeComponent(
  "diagnoz.detail",
  ".default",
  [
    "ACTIVE_DATE_FORMAT"        => "d.m.Y",
    "ADD_ELEMENT_CHAIN"         => "Y",
    "ADD_SECTIONS_CHAIN"        => "N",
    "AJAX_MODE"                 => "N",
    "AJAX_OPTION_ADDITIONAL"    => "",
    "AJAX_OPTION_HISTORY"       => "N",
    "AJAX_OPTION_JUMP"          => "N",
    "AJAX_OPTION_STYLE"         => "Y",
    "BROWSER_TITLE"             => "NAME",
    "CACHE_GROUPS"              => "Y",
    "CACHE_TIME"                => "36000000",
    "CACHE_TYPE"                => "N",
    "CHECK_DATES"               => "Y",
    "DETAIL_URL"                => "",
    "DISPLAY_BOTTOM_PAGER"      => "Y",
    "DISPLAY_DATE"              => "N",
    "DISPLAY_NAME"              => "N",
    "DISPLAY_PICTURE"           => "Y",
    "DISPLAY_PREVIEW_TEXT"      => "Y",
    "DISPLAY_TOP_PAGER"         => "N",
    "ELEMENT_CODE"              => "",
    "ELEMENT_ID"                => $_REQUEST[ "ELEMENT_ID" ],
    "FIELD_CODE"                => [
      0 => "",
      1 => "",
    ],
    "IBLOCK_ID"                 => "28",
    "IBLOCK_TYPE"               => "s1",
    "IBLOCK_URL"                => "",
    "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
    "MESSAGE_404"               => "",
    "META_DESCRIPTION"          => "-",
    "META_KEYWORDS"             => "-",
    "PAGER_BASE_LINK_ENABLE"    => "N",
    "PAGER_SHOW_ALL"            => "N",
    "PAGER_TEMPLATE"            => ".default",
    "PAGER_TITLE"               => "Страница",
    "PROPERTY_CODE"             => [
      0 => "",
      1 => "",
    ],
    "SET_BROWSER_TITLE"         => "Y",
    "SET_CANONICAL_URL"         => "N",
    "SET_LAST_MODIFIED"         => "N",
    "SET_META_DESCRIPTION"      => "Y",
    "SET_META_KEYWORDS"         => "N",
    "SET_STATUS_404"            => "N",
    "SET_TITLE"                 => "N",
    "SHOW_404"                  => "N",
    "USE_PERMISSIONS"           => "N",
    "USE_SHARE"                 => "N",
    "COMPONENT_TEMPLATE"        => ".default",
  ],
  FALSE
); ?><br>
<? $APPLICATION->IncludeComponent(
  "bitrix:main.include",
  "",
  [
    "AREA_FILE_SHOW"   => "page",
    "AREA_FILE_SUFFIX" => "inc",
    "EDIT_TEMPLATE"    => "",
  ]
); ?><br><? require( $_SERVER[ "DOCUMENT_ROOT" ] . "/bitrix/footer.php" ); ?>